/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export interface InstantiateMsg {
  cw420: number;
  description: string;
  event_curator?: string | null;
  event_timeline: EventSegments[];
  guest_details: GuestDetails[];
  title: string;
  usher_admins: Member[];
}
export interface EventSegments {
  end: Timestamp;
  stage_description: string;
  start: Timestamp;
}
export interface GuestDetails {
  guest_type: string;
  guest_weight: number;
  max_guest_limit: number;
  max_ticket_limit: number;
  overbooking_limit: number;
  ticket_cost: Coin[];
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface Member {
  addr: string;
  weight: number;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  purchase_tickets: {
    guests: RegisteringGuest[];
  };
} | {
  check_in_guest: {
    checkin: CheckInDetails;
    stage: number;
  };
} | {
  refund_unconfirmed_tickets: {
    guests: string[];
  };
};
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface RegisteringGuest {
  guest_type: string;
  ticket_wallet: string;
}
export interface CheckInDetails {
  pubkey: Binary;
  signature: Binary;
  ticket_addr: string;
}
export type QueryMsg = {
  config: {};
} | {
  event_stages: {};
} | {
  guest_attendance_status: {
    event_stage_id: number;
    guest: string;
  };
} | {
  guest_attendance_status_a_l_l: {
    guest: string;
  };
};
export type Addr = string;
export interface Config {
  curator: string;
  event_guest_contract: Addr;
  event_usher_contract: Addr;
  title: string;
}
export type ArrayOfEventSegments = EventSegments[];
export type Boolean = boolean;
export type ArrayOfBoolean = boolean[];