/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Timestamp, Uint64, Uint128, InstantiateMsg, EventSegments, GuestDetails, Coin, Member, ExecuteMsg, Binary, Cw20ReceiveMsg, RegisteringGuest, CheckInDetails, QueryMsg, Addr, Config, ArrayOfEventSegments, Boolean, ArrayOfBoolean } from "./CwAve.types";
export interface CwAveReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  eventSegments: () => Promise<ArrayOfEventSegments>;
  guestAttendanceStatus: ({
    eventStageId,
    guest
  }: {
    eventStageId: number;
    guest: string;
  }) => Promise<Boolean>;
  guestAttendanceStatusALL: ({
    guest
  }: {
    guest: string;
  }) => Promise<ArrayOfBoolean>;
}
export class CwAveQueryClient implements CwAveReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.eventSegments = this.eventSegments.bind(this);
    this.guestAttendanceStatus = this.guestAttendanceStatus.bind(this);
    this.guestAttendanceStatusALL = this.guestAttendanceStatusALL.bind(this);
  }

  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  eventSegments = async (): Promise<ArrayOfEventSegments> => {
    return this.client.queryContractSmart(this.contractAddress, {
      event_stages: {}
    });
  };
  guestAttendanceStatus = async ({
    eventStageId,
    guest
  }: {
    eventStageId: number;
    guest: string;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guest_attendance_status: {
        event_stage_id: eventStageId,
        guest
      }
    });
  };
  guestAttendanceStatusALL = async ({
    guest
  }: {
    guest: string;
  }): Promise<ArrayOfBoolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guest_attendance_status_a_l_l: {
        guest
      }
    });
  };
}
export interface CwAveInterface extends CwAveReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  purchaseTickets: ({
    guests
  }: {
    guests: RegisteringGuest[];
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  checkInGuest: ({
    checkin,
    stage
  }: {
    checkin: CheckInDetails;
    stage: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  refundUnconfirmedTickets: ({
    guests
  }: {
    guests: string[];
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class CwAveClient extends CwAveQueryClient implements CwAveInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.purchaseTickets = this.purchaseTickets.bind(this);
    this.checkInGuest = this.checkInGuest.bind(this);
    this.refundUnconfirmedTickets = this.refundUnconfirmedTickets.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, funds);
  };
  purchaseTickets = async ({
    guests
  }: {
    guests: RegisteringGuest[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      purchase_tickets: {
        guests
      }
    }, fee, memo, funds);
  };
  checkInGuest = async ({
    checkin,
    stage
  }: {
    checkin: CheckInDetails;
    stage: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      check_in_guest: {
        checkin,
        stage
      }
    }, fee, memo, funds);
  };
  refundUnconfirmedTickets = async ({
    guests
  }: {
    guests: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      refund_unconfirmed_tickets: {
        guests
      }
    }, fee, memo, funds);
  };
}