/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwAve.types";
import * as _1 from "./CwAve.client";
import * as _2 from "./CwAve.message-composer";
import * as _3 from "./CwAve.react-query";
import * as _4 from "./CwAveFactory.types";
import * as _5 from "./CwAveFactory.client";
import * as _6 from "./CwAveFactory.message-composer";
import * as _7 from "./CwAveFactory.react-query";
export namespace contracts {
  export const CwAve = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const CwAveFactory = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
}